plugins:
  - name: crystal
    default_version: 1.3.2
    versions:
      - 1.3.0
      - 1.2.1
      - 1.2.0
  - name: elixir
    default_version: 1.13.2-otp-24
  - name: erlang
    default_version: 24.2.1
  - name: golang
    default_version: 1.17.7
    versions:
      - 1.16.5
  - name: ruby
    default_version: 3.0.2
