plugins:
  - name: crystal
    default_version: "1.5.0"
  - name: elixir
    default_version: 1.15.4-otp-26
  - name: erlang
    default_version: "26.0.2"
  - name: golang
    default_version: "1.20.2"
  - name: ruby
    default_version: "3.2.2"
  - name: rust
    default_version: "1.71.0"
  - name: terraform
    default_version: "1.5.3"
