plugins:
  - name: crystal
    default_version: "1.5.0"
    versions:
      - "1.3.2"
      - "1.2.1"
      - "1.2.0"
  - name: elixir
    default_version: 1.14.0-otp-25
    versions:
      - "1.13.4-otp-25"
      - "1.12.3"
      - 1.12.3-otp-24
  - name: erlang
    default_version: "25.0.3"
    versions:
      - "24.3.4"
  - name: golang
    default_version: "1.18.4"
    versions:
      - "1.17.12"
  - name: ruby
    default_version: "3.0.2"
    versions:
      - "3.0.2"
      - "2.7.6"
  - name: rust
    default_version: "1.62.1"
  - name: terraform
    default_version: "1.2.5"
